name: ğŸ· Tag and release

on:
  push:
    paths:
      - version
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out code
        uses: actions/checkout@v3

      - name: ğŸ· Create a tag
        id: create-tag
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: 'lib/crane/version.rb'
          regex_pattern: "(\\d+\\.\\d+\\.\\d+)"
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: ğŸ¦„ Create a release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ steps.create-tag.outputs.tagname }}
          token: ${{ secrets.GITHUB_TOKEN }}
