# Create a new GitHub tag and release based on a value in version file.
---
name: ğŸ· Tag and Release


on:
  push:
    paths:
      - version
    branches: [main, master]


permissions:
  # Required for workflows in private repositories.
  contents: write


jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out code
        uses: actions/checkout@v3

      - name: ğŸ· Create a tag
        id: create-tag
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: "version"
          regex_pattern: "(\\d+\\.\\d+\\.\\d+)"
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: ğŸ¦„ Create a release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ steps.create-tag.outputs.tagname }}
          token: ${{ secrets.GITHUB_TOKEN }}
